sudo: false
language: python
python:
- '3.4'
- '3.5'
install: pip3 install .
script: echo Doing nothing
deploy:
  provider: pypi
  user: uavcan
  password:
    secure: kVFhfNM/2tv4gSID97npYjzrsiTLxMJQzVz265gQGz/8b2zIe36GO63bGfu5mlHFCZaTc7KS/6bOHicP+I1ePHKBVaevgac6Gkr+rtQWSL0KGAqkEar8E6QhdwUURRiwzjf/dHAfgdbN4nqC0TLitROi0W0J0zMjojDwdV5/RV0WGlhOHMMr8yotEAb+lch2cTdIIgkjowSs2In4U/VlAPABtbL6VMTm32kobhK7BknJWoL+FpIxg4T+itXwov/wYEIfGdKqLZGEBojoBE4ucwwiTJ2WnyeNprVLEcbCLtUqXFeVNXam1caByxb1h8NSIaE0q1bLfNwgU8wTmILVpvOKPiAAThMiTTaUkJ6qcn97EtZjWVx3VcXhy6RwSskutSDEZHLxZPuNDwR3dlAqFGYufM0HMMlV5onGona2zGNyjjpXl1oHpiIEz4v4HUWrvzzd3Dj6lbptf2SUpkPljz5ukd4WbzsVlWgAffFSVzs46vIJiK3W7tfBPKQieB6VJSOIRMzHWoGf3p3yX60RuGJ/cosAHvr0nY7nF9JgQazX1UOsxwAj438jiqy4YP8PZBptchGh9fRoA7+kiVCszWHrvnPuPzuGJanSN5b4GMeTJcBrTWrmJt64MzVPSszCsVAwqTazlzXp5/QyV4c8rTvPoduZQt0Dt3hRLPUtmJ8=
  on:
    tags: true
    repo: UAVCAN/gui_tool
  distributions: bdist_wheel
  skip_cleanup: true
